### ISSUE TITLE
low R@1 performance when reload training best weights

### ISSUE THREAD

**Issue by smuelpeng** [Ziyang412/UCoFiA#2]
Dear Ziyang

Firstly, I'd like to express my appreciation for your work on UCoFiA, which has been highly inspiring. However, I've encountered a discrepancy in the reproduction performance, particularly with the R@1 results, which are lower than those reported in your paper.

Using the provided weights ([link](https://drive.google.com/file/d/1-zynuNEI1u0TwNxw2R163kX4kocWDsIu/view?usp=sharing)), my Text-to-Video R@1 result on original videos is 49.6%. This contrasts with the results obtained during training, where the best checkpoint achieved a R@1 of 47.6%, and testing on this checkpoint at the end of training yielded 46.6%. Further testing using the eval_msrvtt.sh script from the eval_t2v folder resulted in a R@1 of 47.5%.

I have attempted to address this issue by following the recommendations in [this GitHub issue](https://github.com/Ziyang412/UCoFiA/issues/1), including using the 'test-original' setting and adjusting the training epochs to 5, 8, and 15. Unfortunately, these adjustments did not resolve the discrepancy.

Could you provide any guidance or suggestions on how to align the reproduction results more closely with those reported in your paper? Any advice or additional troubleshooting steps would be greatly appreciated.

Thank you for your time and assistance.

Best regards,

Zhipeng

**Comment by Ziyang412** [comment]
Hi, thanks for your attention to our work. Could you provide more detail about the CUDA/Pytorch version and your GPU type? I am using 4*A5000 for my best experiments (and the Pytorch version provided in the repo). Also, please check whether your video is compressed to 3FPS 224*224. Hope it helps! 

-Ziyang

**Comment by smuelpeng** [comment]
I compressed the video with a script found at https://github.com/Ziyang412/UCoFiA/blob/main/train/preprocess/compress_video.py#L26. This script compresses the video to a width of 224 pixels along its shorter side, rather than adjusting the video to a uniform resolution of 224x224. I'm not sure whether this method is appropriate.

For my experiments, I worked with four 3090 GPUs in an environment that included Python version 3.8, Torch version 1.12.1, and CUDA version 11.6.

**Comment by Ziyang412** [comment]
I think the possible reason is the GPU type. I think I saw from another repo that deep learning special GPU A100/A6000/A5000 / V100 will perform better than 20xx/30xx GPUs. I am using 4* Nvidia A5000 GPUs for all my exps, I highly recommend you try the experiments on other datasets.

**Comment by Ziyang412** [comment]
I think the problem is the GPU, I saw from another repo that 20xx/30xx have less performance than A-series. I am using 4* NVIDIA A5000 GPUs for all my exps. High recommend checking on other servers. Sorry for that, and hope it helps.

**Comment by smuelpeng** [comment]
I gave another try on a configuration of 4 A800 GPUs and obtained a result of 48.3, but there's still some gap from 49.4.
Additionally, while testing the provided pytorch_model.bin.5, I encountered several error messages, which leads me to suspect that there might be missing elements in the algorithmic details. I have attached a screenshot for your reference.
![image](https://github.com/Ziyang412/UCoFiA/assets/3851022/34c63420-71cc-4bef-8d7e-739fb774ca0f)
 I wonder if there are some algorithmic details that were missed.
 I will try it again on A5000, still grateful for your contribution to the community!

**Comment by Ziyang412** [comment]
Hey, thanks for the detailed investigation of our work. I think I probably know where the problem is and updated both differential_topk.py under /train and /eval_v2t root. Please check it out with the latest version and let me know whether it fixed the problem. Thanks.
