### ISSUE TITLE
测试 eval_msrvtt.sh 时，遇到size mismatch报错

### ISSUE THREAD

**Issue by lexilii** [Ziyang412/UCoFiA#3]
Weights from pretrained model cause errors in UCoFiA: 
   size mismatch for visual_token_selector.score_predictor.in_conv.0.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
   size mismatch for visual_token_selector.score_predictor.in_conv.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
   size mismatch for visual_token_selector.score_predictor.in_conv.1.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([512, 1024]).
   size mismatch for visual_token_selector.score_predictor.out_conv.0.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([512, 1024]).
   size mismatch for visual_token_selector.score_predictor.out_conv.2.weight: copying a param with shape torch.Size([1, 256]) from checkpoint, the shape in current model is torch.Size([1, 512]).

**Comment by Ziyang412** [comment]
Please refer to here https://github.com/Ziyang412/UCoFiA/issues/2#issuecomment-2002585864, thanks!
