### ISSUE TITLE
Which line is the implementation of Interactive Similarity Attention (ISA)?

### ISSUE THREAD

**Issue by longmalongma** [Ziyang412/UCoFiA#5]
Hi, Which line is the implementation of Interactive Similarity Attention (ISA)?

**Comment by longmalongma** [comment]
![image](https://github.com/Ziyang412/UCoFiA/assets/40291722/2e0d101e-534b-46f8-910c-349d95c0425e)
In  Interactive Similarity Attention (ISA) module,  What if there is an ever-growing t (increasing number of video frames) dimension?

**Comment by Ziyang412** [comment]
Hi, sorry for not explicitly mention in the code.

For ISA, please check line 352-353
https://github.com/Ziyang412/UCoFiA/blob/517f838483af544304482bc70ee7ff4886d3dfc6/train/modules/modeling_ucofia.py#L352

For Bi-ISA, please check line 360-368 https://github.com/Ziyang412/UCoFiA/blob/517f838483af544304482bc70ee7ff4886d3dfc6/train/modules/modeling_ucofia.py#L360

I think the problem of " ever-growing t" is out of scope of our work, but it's an meaningful future direction to work on, thanks!
