### ISSUE TITLE
where I can get cross_pytorch_model.bin file

### ISSUE THREAD

**Issue by 11362p** [Ziyang412/UCoFiA#6]
05/16/2024 23:14:17 - INFO -   Weight doesn't exsits. F:\PaperCode\UCoFiA-main\train\modules\cross-base\cross_pytorch_model.bin

**Comment by 11362p** [comment]
Is the cross_pytorch_model.bin file downloaded from the url given in the README file?
https://drive.google.com/file/d/1-zynuNEI1u0TwNxw2R163kX4kocWDsIu/view?usp=sharing
I'm not sure if I understand the paper wrongly. Which dataset did you pre-train on? I don't seem to find the relevant pre-training description. Can you help me answer this question? Thanks

**Comment by Ziyang412** [comment]
Hi, I think we do not initialize the cross-attn model but train the model, I assume this is a warning not a error? You could just ignore it thanks!
