### ISSUE TITLE
请问我应该如何进行可视化的测试

### ISSUE THREAD

**Issue by sizhandailiawa** [Ziyang412/UCoFiA#9]

**Comment by Ziyang412** [comment]
Thanks for asking. Could you please provide more details for your question?

**Comment by sizhandailiawa** [comment]
> 谢谢你的提问。中方能否就您的问题提供更多详情？

只看到了您代码中训练和评估的部分，为能找到测试部分。

**Comment by sizhandailiawa** [comment]
> 谢谢你的提问。中方能否就您的问题提供更多详情？

只看到了您代码中训练和评估的部分，未能找到测试部分。

**Comment by Ziyang412** [comment]
Hi, we followed the settings of [CLIP4Clip](https://github.com/ArrowLuo/CLIP4Clip) and introduced in our paper. Please refer to the Experimental Setup section of our paper and the original CLIP4Clip repo/paper for more details. Thanks!
